## Custom Fields [/customFieldDefinitions]

### customFieldDefinitions.list [GET /customFieldDefinitions.list]

Get a list of all the definitions of custom fields.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + context: `contact` (enum[string], required) - The context of the custom field definition
            + Members
                + contact
                + company
                + deal
                + project
                + milestone
                + product
                + invoice
                + subscription
                + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                + ticket

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id (string)
                + context: `contact` (enum[string])
                    + Members
                        + contact
                        + company
                        + deal
                        + project
                        + milestone
                        + product
                        + invoice
                        + subscription
                        + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                        + ticket
                + type (enum[string])
                    + Members
                        + single_line - Single line text
                        + multi_line - Multiline text
                        + single_select - Single selection
                        + multi_select - Multiple selection
                        + date - Date
                        + money - Money
                        + auto_increment - Automatically incrementing field
                        + integer - Integer
                        + number - Number
                        + boolean - Yes/No
                        + email - Email address
                        + telephone - Phone number
                        + url - URL
                        + company - Company
                        + contact - Contact
                        + product - Product
                        + user - User
                + label (string)
                + required: `false` (boolean)
                + options: foo, bar (array[string], nullable)
                + client (object) - The oauth client that is the owner for this custom field definition
                    + type: `client` (string)
                    + id: `123` (string)
                + readable (enum[string])
                    + Members
                        + by_owning_client
                        + by_all_clients
                + writable (enum[string])
                    + Members
                        + by_owning_client
                        + by_all_clients

### customFieldDefinitions.info [GET /customFieldDefinitions.info]

Get a info about a specific custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `20` (number, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id (string)
            + context: `contact` (enum[string])
                + Members
                    + contact
                    + company
                    + deal
                    + project
                    + milestone
                    + product
                    + invoice
                    + subscription
                    + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                    + ticket
            + type (enum[string])
                + Members
                    + single_line - Single line text
                    + multi_line - Multiline text
                    + single_select - Single selection
                    + multi_select - Multiple selection
                    + date - Date
                    + money - Money
                    + auto_increment - Automatically incrementing field
                    + integer - Integer
                    + number - Number
                    + boolean - Yes/No
                    + email - Email address
                    + telephone - Phone number
                    + url - URL
                    + company - Company
                    + contact - Contact
                    + product - Product
                    + user - User
            + label (string)
            + required: `false` (boolean)
            + options: foo, bar (array[string], nullable)
            + client (object) - The oauth client that is the owner for this custom field definition
                + type: `client` (string)
                + id: `123` (string)
            + readable (enum[string])
                + Members
                    + by_owning_client
                    + by_all_clients
            + writable (enum[string])
                + Members
                    + by_owning_client
                    + by_all_clients

### customFieldDefinitions.add [POST /customFieldDefinitions.add]

Add a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + context: `contact` (enum[string], required)
            + Members
                + contact
                + company
                + deal
                + project
                + milestone
                + product
                + invoice
                + subscription
                + activity - Will be available on both calendar events & todos, as they are convertable to eachother
                + ticket
        + type (enum[string], required)
            + Members
                + single_line - Single line text
                + multi_line - Multiline text
                + single_select - Single selection
                + multi_select - Multiple selection
                + date - Date
                + money - Money
                + auto_increment - Automatically incrementing field
                + integer - Integer
                + number - Number
                + boolean - Yes/No
                + email - Email address
                + telephone - Phone number
                + url - URL
                + company - Company
                + contact - Contact
                + product - Product
                + user - User
        + label (string, required)
        + required: `false` (boolean, optional)
        + options: 1, 2 (array[string], optional)
        + readable (enum[string], required)
            + Members
                + by_owning_client
                + by_all_clients
        + writable (enum[string], required)
            + Members
                + by_owning_client
                + by_all_clients

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + id (string)

### customFieldDefinitions.update [POST /customFieldDefinitions.update]

Add a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id (string)
        + label (string, optional)
        + required: `false` (boolean, optional)
        + options: 1, 2 (array[string], optional)
        + readable (enum[string], optional)
            + Members
                + by_owning_client
                + by_all_clients
        + writable (enum[string], optional)
            + Members
                + by_owning_client
                + by_all_clients

+ Response 204 (application/json;charset=utf-8)

### customFieldDefinitions.delete [POST /customFieldDefinitions.delete]

Delete a custom field definition

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `20` (number, required)

+ Response 204
