## Users [/users]

### users.list [GET /users.list]

Get a list of all users.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `1` (number)
                + name: `John Smith` (string)
                + email: `john@teamleader.eu` (string)
                + gsm: `+32412654321` (string)
                + phone: `+3291239843` (string)
                + team (object)
                    + type: `team` (string, required)
                    + id: 1 (number)
                + title: `Sales` (string)
                + active: `true` (boolean)
