## Settings [/invoicing]

### taxRates.list [GET /taxRates.list]

List tax rates

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids (array[string], optional)
            + department_id: `66766830-3bd0-41b2-a279-5987aa6153c2` (string, optional) - The ID of the department you wish to filter on.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `c93ddb52-0af8-47d9-8551-441435be66a7` (string)
                + description: `21%` (string)
                + rate: `0.21` (number)