## Products [/products]

### products.list [GET /products.list]

+ Request (application/json)

    + Attributes (object)
        + ids: 1,2 (array[string], optional)
        + page (object, optional)
            + size: `20` (number, optional) - The amount of products returned per request, max 1 to 100
                + Default: `20`
            + number: `1` (number, optional) - The current page, the first page is 1
                + Default: `1`

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `1` (string)
                + translations (object)
                    + _items (array)
                        + (object)
                            + language: `EN` (string)
                            + name: `Product name` (string)
                            + description: `Product description` (string)
                + default_language (string)
                + prices (array)
                    + (object)
                        + price_list (object, nullable)
                            + type: `priceList` (string)
                            + id: `1` (string)
                        + price (ReadPrice)

### products.info [GET /products.info]

+ Request (application/json)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + id: `1` (string)
        + translations (object)
            + _items (array)
                + (object)
                    + language: `EN` (string)
                    + name: `Product name` (string)
                    + description: `Product description` (string)
        + default_language (string)
        + prices (array)
            + (object)
                + price_list (object, nullable)
                    + type: `priceList` (string)
                    + id: `1` (string)
                + price (ReadPrice)
        + custom_fields (object)
            + _items (array)
                + (object)
                    + field (object)
                        + _type: `customField`
                        + id: 123 (string)
                    + value: `092980616`

### products.add [POST /products.add]

+ Request (application/json)

    + Attributes (object)
        + translations (array, required)
            + (object)
                + language: `EN` (string, required)
                + name: `Product name` (string, required)
                + description: `Product description` (string, optional)
        + default_language (string, required)
        + prices (array[WritePrice], required)
        + custom_fields (array, optional)
            + (object)
                + custom_field_id: 123 (string, required)
                + value: `092980616` (required)

+ Response 201 (application/json)

    + Attributes (object)
        + id: `1` (string)

### products.update [POST /products.update]

+ Request (application/json)

    + Attributes (object)
        + id (string, required)
        + translations (array, optional)
            + (object)
                + language: `EN` (string, required)
                + name: `Product name` (string, required)
                + description: `Product description` (string, optional)
        + default_language (string, optional)
        + prices (array[WritePrice], optional)
        + custom_fields (array, optional)
            + (object)
                + custom_field_id: 123 (string, required)
                + value: `092980616` (required)

+ Response 204 (application/json)

### products.delete [POST /products.delete]

+ Request (application/json)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204 (application/json)

### priceLists.list [GET /pricelists.list]

+ Request (application/json)

    + Attributes (object)
        + ids: 1,2 (array[string], optional)
        + page (object, optional)
            + size: `20` (number, optional) - The amount of pricelists returned per request, max 1 to 100
                + Default: `20`
            + number: `1` (number, optional) - The current page, the first page is 1
                + Default: `1`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + type: `priceList` (string)
                + id: `1` (string)
                + description: `Default (EUR)` (string, nullable)
                + default: `EUR` (string, nullable)
