## Milestones [/milestones]

### milestones.list [GET /milestones.list]

Get a list of project milestones.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids (array[string], optional)
            + project_id (string, optional)
            + status (enum[string], optional)
                + Members
                    + open
                    + closed
            + due_before: `2017-01-01` (string, optional)
            + due_after: `2017-01-01` (string, optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `1` (string)
                + project (object)
                    + type: `project` (string)
                    + id: `2` (string)
                + due_on: `2018-01-01` (string)
                + name: `Initial setup` (string)
                + status: `done` (enum[string])
                    + Members
                        + open
                        + closed

### milestones.info [GET /milestones.info]

Get details for a single milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `1` (string)
            + project (object)
                + type: `project` (string)
                + id: `2` (string)
            + due_on: `2018-01-01` (string)
            + name: `Initial setup` (string)
            + status: `done` (enum[string])
                + Members
                    + open
                    + closed

### milestones.create [POST /milestones.create]

Create a new milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + project_id: `2` (string, required)
        + due_on: `2018-01-01` (string, required)
        + name: `Initial setup` (string, required)

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + type: `milestone` (string)
            + id: `1` (string)

### milestones.update [POST /milestones.update]

Update a milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + due_on: `2018-01-01` (string, optional)
        + name: `Initial setup` (string, optional)

+ Response 204 (application/json;charset=utf-8)

### milestones.close [POST /milestones.close]

Close a milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204 (application/json;charset=utf-8)

### milestones.reopen [POST /milestones.reopen]

Open a closed milestone.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204 (application/json;charset=utf-8)
