## Deals [/deals]

### deals.list [GET /deals.list]

Get a list of deals.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + filter (object, optional)
            + term: `Teamleader` (string, optional) - A search string. Teamleader will try to search deals matching this string.
            + phase_id: `5` (string, optional) - Only return deals with this phase ID
            + company_id: `123` (string, optional) - Only return deals for this company
            + contact_id: `456` (string, optional) - Only return deals for this contact
            + responsible_user_id: `456` (string, optional) - Only return deals for this user
        + sort (array, optional)
            + (object)
                + field: `created_at` (enum[string], required)
                    + Members
                        + created_at
                    + Default: `created_at`
                + order: `desc` (enum[string], optional)
                    + Members
                        + desc
                    + Default: `created_at`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `164938` (string)
                + title: `Interesting deal` (string)
                + reference: `2017/2` (string)
                + status: `won` (enum[string])
                    + Members
                        + open
                        + won
                        + lost
                + customer (object)
                    + type: `contact`
                    + id: 1 (string)
                + department (object)
                    + type: `department`
                    + id: 1 (string)
                + estimated_value (Money)
                + estimated_closing_date: `2017-05-09` (string)
                + estimated_probability: `0.5` (number)
                + current_phase (object)
                    + type: `dealPhase`
                    + id: 1 (string)
                + responsible_user (object)
                    + type: `user`
                    + id: 1 (string)
                + closed_at: `2017-05-09T11:31:30+00:00` (string)
                + lost (object)
                    + reason (object)
                        + type: `lostReason` (string)
                        + id (string)
                    + extra_info (string, optional)
                + source (object)
                    + type: `dealSource` (string)
                    + id (string)
                + custom_fields (array)
                    + (object)
                        + field (object)
                            + type: `customField`
                            + id: 123 (string)
                        + value: `092980616`
                + created_at: `2017-05-09T11:25:11+00:00` (string)
                + updated_at: `2017-05-09T11:30:58+00:00` (string)

### deals.info [GET /deals.info]

Get details for a single deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + id: `164938` (string)
        + title: `Interesting deal` (string)
        + reference: `2017/2` (string)
        + status: `won` (enum[string])
            + Members
                + open
                + won
                + lost
        + customer (object)
            + type: `contact` (string)
            + id: 123 (string)
        + department (object)
            + type: `department`
            + id: 1 (string)
        + estimated_value (Money)
        + estimated_closing_date: `2017-05-09` (string)
        + estimated_probability: `0.5` (number)
        + current_phase (object)
            + type: dealPhase (string)
            + id: `5` (string)
        + responsible_user (object)
            + type: user (string)
            + id: 17 (string)
        + closed_at: `2017-05-09T11:31:30+00:00` (string)
        + lost (object)
            + reason (object)
                + type: `lostReason` (string)
                + id (string)
            + extra_info (string, optional)
        + source (object)
            + type: `dealSource` (string)
            + id (string)
        + custom_fields (array)
            + (object)
                + field (object)
                    + type: `customField`
                    + id: 123 (string)
                + value: `092980616`
        + phase_history (array)
            + (object)
                + phase (object)
                    + type: dealPhase (string)
                    + id: `1` (string)
                + started_at: `2017-05-01 12:00:00` (string)
                + started_by (object)
                    + type: user (string)
                    + id: `5` (string)
                + ended_at: `2017-05-01 12:00:00` (string)
                + ended_by (object)
                    + type: user (string)
                    + id: `5` (string)
        + created_at: `2017-05-09T11:25:11+00:00` (string)
        + updated_at: `2017-05-09T11:30:58+00:00` (string)

### deals.create [POST /deals.create]

Create a new deal for a customer.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object)
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: 123 (string)
        + title: `Interesting business deal` (string, required)
        + source (object, optional)
            + type: `dealSource` (string, required)
            + id: `1` (string, required)
        + department (object, optional)
            + type: `dealSource` (string, required)
            + id: `1` (string, required)
        + responsible_user (object, optional)
            + type: `user` (string, required)
            + id: `1` (string, required)
        + phase (object, optional)
            + type: `dealPhase` (string, required)
            + id: `1` (string, optional)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional)
        + estimated_closing_date: `2017-05-09` (string, optional)
        + custom_fields (array)
            + (object)
                + field (object)
                    + type: `customField`
                    + id: 123 (string)
                + value: `092980616`

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + data (object)
            + id: `1` (string)

### deals.update [POST /deals.update]

Update a deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + title: `Interesting business deal` (string, optional)
        + source (object, optional)
            + type: `dealSource` (string, required)
            + id: `1` (string, required)
        + department (object, optional)
            + type: `dealSource` (string, required)
            + id: `1` (string, required)
        + responsible_user (object, optional)
            + type: `user` (string, required)
            + id: `1` (string, required)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional)
        + estimated_closing_date: `2017-05-09` (string, optional)
        + custom_fields (array)
            + (object)
                + field (object)
                    + type: `customField`
                    + id: 123 (string)
                + value: `092980616`

+ Response 204

### deals.move [POST /deals.move]

Move the deal to a different phase.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + phase (object, required)
            + type: `dealPhase` (string, required)
            + id: `1` (string, required)

+ Response 204

### deals.won [POST /deals.won]

Mark a deal as won.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204

### deals.lost [POST /deals.lost]

Mark a deal as lost.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + phase (object, required)
            + type: `lostReason` (string, required)
            + id: `1` (string, required)
        + extra_info: `Not ready for a change, decision postponed` (string, optional)

+ Response 204
