## Settings [/]

### tags.list [GET /tags.list]

Get a list of all tags.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data : expo, upsell (array[string])

### companyTypes.list [GET /companyTypes.list]

Get the names of business types (legal structures) a company can have within a certain country.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + country: `BE` (string)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data: `BVBA`, `NV` (array[string])

### dealPhases.list [GET /dealPhases.list]

Get a list of all phases a deal can go through.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `21efc56e-1ba8-469d-926a-e89502591b47` (string)
            + name: `New` (string)


### dealSources.list [GET /dealSources.list]

Get a list of all deal sources.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `b18c298b-0e6f-495d-8fcd-31dfecaea741` (string)
            + description: `Referral` (string)


### lostReasons.list [GET /lostReasons.list]

Get a list of all deal sources.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array[object])
            + id: `c64247f0-d5b1-46e1-befe-bf85f3fae352` (string)
            + description: `Lost to competitor` (string)
