## Settings [/activities]

### activityTypes.list [GET /activityTypes.list]

Get a list of all activity types.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id (string)
                + name (string)
                + color (string)
                + icon (string)

### topics.list [GET /topics.list]

Get a list of all topics.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id (string)
                + name (string)
                + hourly_rate (number)
                + ledger_account (string)
                + billable (boolean)
