## Settings [/activities]

### activityTypes.list [GET /activityTypes.list]

Get a list of all activity types.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `9feb5f61-c6dd-4f9d-9b37-2813ada4e343` (string)
                + name (string)
                + color (string)
                + icon (string)

### topics.list [GET /topics.list]

Get a list of all topics.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `811a5825-96f4-4318-83c3-2840935c6003` (string)
                + name (string)
                + hourly_rate (number)
                + ledger_account (string)
                + billable (boolean)
