FORMAT: 1A
HOST: https://api.teamleader.eu

# Teamleader API

:[Introduction](introduction.apib)

:[OAuth2](oauth2.apib)

:[General](general.apib)

:[Calendar entries](calendar-entries.apib)

:[Contacts](contacts.apib)

:[Companies](companies.apib)

:[Deals](deals.apib)

:[Departments](departments.apib)

:[Invoices](invoices.apib)

:[Meetings](meetings.apib)

:[Milestones](milestones.apib)

:[Web hooks](webHooks.apib)

:[Data Structures](datastructures.apib)
