FORMAT: 1A
HOST: https://api.teamleader.eu

# Teamleader API

:[Introduction](introduction.apib)

:[OAuth2](oauth2.apib)

# Group General

:[General](general.apib)

:[Departments](departments.apib)

:[Products](products.apib)

# Group CRM

:[Contacts](contacts.apib)

:[Companies](companies.apib)

:[Deals](deals.apib)

:[Quotations](quotations.apib)

# Group Activities

:[Events](events.apib)

:[Todos](todos.apib)

:[Timetracking](timetracking.apib)

# Group Invoicing

:[Invoices](invoices.apib)

:[Subscriptions](subscriptions.apib)

# Group Projects

:[Projects](projects.apib)

:[Milestones](milestones.apib)

# Group Other

:[Attachments](files.apib)

:[Web hooks](webHooks.apib)

:[Data Structures](datastructures.apib)
