## Calendar entries [/calendar-entries]

### calendarEntries.list [GET /calendarEntries.list]

Search calendar entries

+ Request (application/json)

    + Attributes (object)
        + filter (object, required)
            + employee_id: `1` (number, required) - Use this to filter by employee
            + start_date: `2017-01-01` (string, required) - Format ISO 8601: yyyy-mm-dd
            + end_date: `2017-01-01` (string, required) - Format ISO 8601: yyyy-mm-dd

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `123` (number)
                + name: `Erlich Bachman's birthday` (string)
                + date: `2017-05-16` (string)
                + duration: `140` (number)
