## Calendar entries [/calendar-entries]

### calendarEntries.list [GET /calendarEntries.list]

Search calendar entries

+ Request (application/json)

    + Attributes (object)
        + filter (object, required)
            + type: `full-day` (enum[string], required) - Use this to filter by type
                + Members
                    + full-day
            + employee_id: `1` (number, required) - Use this to filter by employee
            + start_date: `2017-01-01` (string, required) - Format ISO 8601: yyyy-mm-dd
            + end_date: `2017-01-01` (string, required) - Format ISO 8601: yyyy-mm-dd

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[CalendarEntry])
