## Contacts [/contacts]

### contacts.list [GET /contacts.list]

Get a paginated list of contacts

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + company_id: `1` (number, optional) - Filter contacts by a certain company.
            + updated_since: `2017-04-26T10:01:49+00:00` (string, optional) - ISO 8601 date. Teamleader will only return contacts that have been added or modified since that time (inclusive).
        + page (object, optional)
            + size: `20` (number, optional) - Amount of contacts you want returned, 1 to 100.
                + Default: `20`
            + number: `1` (number, optional) - The numerated page you want, starts at 1.
                + Default: `1`

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[Contact])

### contacts.info [GET /contacts.info]

Get the details for a single contact

+ Request (application/json)

    + Attributes (object)
        + `contact_id`: `1` (number, required)

+ Response 200 (application/json)

    + Attributes (object)
        + data (ContactDetail)

### contacts.add [POST /contacts.create]

Add a contact to Teamleader

+ Request (application/json)

    + Attributes (object)
        + first_name: `John` (string, required) - The first name of the new contact
        + last_name: `Smith` (string, required) - The last name of the new contact
        + email: `john@example.com` (string, required) - The email address of the new contact
        + salutation: `Mr` (string, optional)
        + email: `john@example.com` (string, required) - The email address of the new contact
        + invoice_email: `invoicing@example.com` (string, optional)
        + phone: `1234567` (string, optional)
        + mobile: `7654321` (string, optional)
        + fax: `7654321` (string, optional)
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + language: `EN` (string, optional) - Language code according to ISO 639-1. For Dutch: "NL"
        + gender: `M` (enum[string], optional)
            + Members
                + M
                + F
                + U
        + birthdate: `1989-08-19` (string, optional)
        + remarks: `Met at expo` (string, optional) - Background information on the contact
        + tags: expo, upsell (array[string], optional) - Pass one or more tags. Existing tags will be reused, other tags will be automatically created for you.

+ Response 201 (application/json)

    + Attributes
        + data (object)
            + id: `1` (number)

### contacts.update [POST /contacts.update]

Update a Teamleader contact

+ Request (application/json)

    + Attributes (object)
        + contact_id: `1` (number, required) - The ID of the contact you want to update
        + first_name: `John` (string) - The given name of the new contact
        + last_name: `Smith` (string) - The last name of the new contact
        + salutation: `Mr` (string, optional)
        + email: `john@example.com` (string, required) - The email address of the new contact
        + invoice_email: `invoicing@example.com` (string, optional)
        + phone: `1234567` (string, optional)
        + mobile: `7654321` (string, optional)
        + fax: `7654321` (string, optional)
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + language: `EN` (string, optional) - Language code according to ISO 639-1. For Dutch: "NL"
        + gender: `M` (enum[string], optional)
            + Members
                + M
                + F
                + U
        + birthdate: `1989-08-19` (string, optional)
        + remarks: `Met at expo` (string, optional) - Background information on the contact
        + tags: expo, upsell (array[string], optional) - Pass one or more tags. Existing tags will be reused, other tags will be automatically created for you.

+ Response 204

### contacts.delete [POST /contacts.delete]

Delete a contact from Teamleader

+ Request (application/json)

    + Attributes (object)
        + contact_id: `1` (number, required) - The account ID of the contact you wish to delete

+ Response 204

### contacts.tag [POST /contacts.tag]

Add a tag to a contact

+ Request (application/json)

    + Attributes (object)
        + contact_id: `123` (number, required) - The ID of a contact
        + tags: prospect, expo (array[string], required) - A list of tags to add

+ Response 204

### contacts.untag [POST /contacts.untag]

Remove a tag from a contact

+ Request (application/json)

    + Attributes (object)
        + contact_id: `123` (number, required) - The ID of a contact
        + tags: prospect, expo (array[string], required) - A list of tags to remove

+ Response 204

### contacts.linkToCompany [POST /contacts.linkToCompany]

Linking a contact to a company

+ Request (application/json)

    + Attributes (object)
        + contact_id: `123` (number, required) - The ID of a contact
        + company_id: `5` (number, required) - The ID of a company

+ Response 204

### contacts.unlinkFromCompany [POST /contacts.unlinkFromCompany]

Unlinking a contact from a company

+ Request (application/json)

    + Attributes (object)
        + contact_id: `123` (number, required) - The ID of a contact
        + company_id: `5` (number, required) - The ID of a company

+ Response 204
