## Contacts [/contacts]

### contacts.list [GET /contacts.list]

Get a list of contacts.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + filter (object, optional)
            + ids (array[string], optional)
            + company_id: `1` (string, optional)
            + term: `teamleader` (string, optional)
            + telephone: `092980615` (string, optional)
            + updated_after: `2017-04-26T10:01:49+00:00` (string, optional)
        + page (Page, optional)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `456` (string)
                + first_name: `Erlich` (string)
                + last_name: `Bachman` (string)
                + salutation: `Mr` (string)
                + email: `info@piedpiper.eu` (string)
                + telephones (array[Telephone])
                + website: `https://piedpiper.com` (string)
                + avatar (string)
                + address (Address)
                + gender: `M` (enum[string])
                    + Members
                        + M
                        + F
                        + U
                + birthdate: `1987-04-25` (string)
                + iban: `BE12123412341234` (string)
                + bic: `BICBANK` (string)
                + tags (object)
                    + _items: tag1, tag2 (array[string])
                + custom_fields (object)
                    + _items (array)
                        + (object)
                            + field (object)
                                + _type: `customField` (string)
                                + id: 123 (string)
                            + value: `092980616`
                + companies (object)
                    + _items (array)
                        + (object)
                            + position: `CEO` (string)
                            + decision_maker: true (boolean)
                            + company (object)
                                + _type: `company` (string)
                                + id: 123 (string)
                + language: `en` (string)
                + _meta (object)
                    + added_at: `2016-02-04T16:44:33+00:00` (string)
                    + updated_at: `2016-02-05T16:44:33+00:00` (string)

### contacts.info [GET /contacts.info]

Get details for a single contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + id: `456` (string)
        + first_name: `Erlich` (string)
        + last_name: `Bachman` (string)
        + salutation: `Mr` (string)
        + email: `info@piedpiper.eu` (string)
        + invoice_email: `invoicing@example.com` (string)
        + telephones (array[Telephone])
        + website: `https://piedpiper.com` (string)
        + avatar (string)
        + address (Address)
        + delivery_address (Addressee)
        + visiting_address (Addressee)
        + invoice_address (Addressee)
        + gender: `M` (enum[string])
            + Members
                + M
                + F
                + U
        + birthdate: `1987-04-25` (string)
        + iban: `BE12123412341234` (string)
        + bic: `BICBANK` (string)
        + tags (object)
            + _items: tag1, tag2 (array[string])
        + custom_fields (object)
            + _items (array)
                + (object)
                    + field (object)
                        + _type: `customField` (string)
                        + id: 123 (string)
                    + value: `092980616`
        + companies (object)
            + _items (array)
                + (object)
                    + position: `CEO` (string)
                    + decision_maker: true (boolean)
                    + company (object)
                        + _type: `company` (string)
                        + id: 123 (string)
        + language: `en` (string)
        + remarks: `First contact at expo` (string)
        + _meta (object)
            + added_at: `2016-02-04T16:44:33+00:00` (string)
            + updated_at: `2016-02-05T16:44:33+00:00` (string)

### contacts.add [POST /contacts.add]

Add a new contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + first_name: `John` (string, required)
        + last_name: `Smith` (string, required)
        + email: `john@example.com` (string, required)
        + salutation: `Mr` (string, optional)
        + email: `john@example.com` (string, required)
        + telephones (array[Telephone])
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + language: `en` (string, optional)
        + gender: `M` (enum[string], optional)
            + Members
                + M
                + F
                + U
        + birthdate: `1989-08-19` (string, optional)
        + remarks: `Met at expo` (string, optional)
        + tags: expo, upsell (array[string], optional)
        + custom_fields (array)
            + (object)
                + custom_field_id: 123 (string)
                + value

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string)

### contacts.update [POST /contacts.update]

Update a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + first_name: `John` (string)
        + last_name: `Smith` (string)
        + salutation: `Mr` (string, optional)
        + email: `john@example.com` (string, required)
        + telephones (array[Telephone])
        + website: `http://example.com` (string, optional)
        + address (Address, optional)
        + delivery_address (Addressee, optional)
        + visiting_address (Addressee, optional)
        + invoice_address (Addressee, optional)
        + language: `en` (string, optional)
        + gender: `M` (enum[string], optional)
            + Members
                + M
                + F
                + U
        + birthdate: `1989-08-19` (string, optional)
        + remarks: `Met at expo` (string, optional)
        + tags: expo, upsell (array[string], optional)
       + custom_fields (object)
            + _items (array)
                + (object)
                    + custom_field_id: 123 (string)
                    + value

+ Response 204

### contacts.delete [POST /contacts.delete]

Delete a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204

### contacts.tag [POST /contacts.tag]

Add a new or existing tag to a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `123` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

### contacts.untag [POST /contacts.untag]

Remove a tag from a contact.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `123` (string, required)
        + tags: prospect, expo (array[string], required)

+ Response 204

### contacts.linkToCompany [POST /contacts.linkToCompany]

Link a contact to a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `123` (string, required)
        + company_id: `5` (string, required)
        + position: `CEO` (string)
        + decision_maker: true (boolean)

+ Response 204

### contacts.unlinkFromCompany [POST /contacts.unlinkFromCompany]

Unlink a contact from a company.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `123` (string, required)
        + company_id: `5` (string, required)

+ Response 204
