# Data Structures

## Address (object)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## Addressee (object)
+ addressee: `Pied Piper Finance Dep.` (string, optional)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## AgendaItem (object)
+ id: `123` (number)
+ name: `Erlich Bachman's birthday` (string)
+ type: `full-day` (enum[string])
    + Members
        + full-day
+ date: `2017-05-16` (string)
