# Data Structures

## Address (object)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## Addressee (object)
+ addressee: `Pied Piper Finance Dep.` (string, optional)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## AgendaItem (object)
+ id: `123` (number)
+ name: `Erlich Bachman's birthday` (string)
+ type: `full-day` (enum[string])
    + Members
        + full-day
+ date: `2017-05-16` (string)

## Invoice (object)
+ id: `173111` (number)
+ invoice_nr: `5` (number)
+ invoice_nr_detailed: `2017 / 5 (MAIN)` (string)
+ date: `2016-02-04T16:44:33+00:00` (string)
+ due_date: `2016-02-04T16:44:33+00:00` (string)
+ date_paid: `2016-02-04T16:44:33+00:00` (string)
+ paid: `true` (boolean)
+ total_price_excl_vat: `123.00` (number)
+ total_price_incl_vat: `130.38` (number)
+ name: `De Rode Duivels` (string)
+ for_attention_of: `Radja Nainggolan` (string)
+ incasso_recall_costs: `0.00` (number)
+ incasso_interest_amount: `0.00` (number)
+ structured_communication: `+++000/1731/11048+++` (string)
+ contact_or_company: `company` (string)
+ contact_or_company_id: 485906 (number)

## PhaseChange (object)
+ old_phase_id: `1` (number)
+ new_phase_id: `2` (number)
+ change_date: `2017-05-01 12:00:00` (string)
+ changed_by: `5` (number)

## Quotation (object)
+ quotation_nr: `21` (number)
+ total_price_excl_vat: `0.00` (number)
+ items (array[QuotationItem])

## QuotationItem (object)
+ price: `5` (number)
+ amount: `1` (number)
+ vat: `21` (string) - The vat tariff for this line
+ product_id: `1` (number) - ID of the product
+ account: `1` (number) - ID of the bookkeeping account
+ subtitle: `Enable search` (string)

## User (object)
id: `1` (number)
name: `John Smith` (string)
email: `john@teamleader.eu` (string)
gsm: `+32412654321` (string)
phone: `+3291239843` (string)
team_id: `1` (number)
title: `Sales` (string)
active: `true` (boolean)
