# Data Structures

## Address (object)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## Addressee (object)
+ addressee: `Pied Piper Finance Dep.` (string, optional)
+ street: `Newell Road` (string)
+ number: `5230` (string)
+ zipcode: `94020` (string)
+ city: `Palo Alto` (string)
+ country: `US` (string)

## AgendaItem (object)
+ id: `123` (number)
+ name: `Erlich Bachman's birthday` (string)
+ type: `full-day` (enum[string])
    + Members
        + full-day
+ date: `2017-05-16` (string)

## QuotationItem (object)
+ price: `5` (number)
+ amount: `1` (number)
+ vat: `21` (string) - The vat tariff for this line
+ product_id: `1` (number) - ID of the product
+ account: `1` (number) - ID of the bookkeeping account
+ subtitle: `Enable search` (string)

## User (object)
id: `1` (number)
name: `John Smith` (string)
email: `john@teamleader.eu` (string)
gsm: `+32412654321` (string)
phone: `+3291239843` (string)
team_id: `1` (number)
title: `Sales` (string)
active: `true` (boolean)
