## Deals [/deals]

### deals.list [GET /deals.list]

Get a list of deals.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + page (Page, optional)
        + filter (object, optional)
            + term: `Teamleader` (string, optional) - A search string. Teamleader will try to search deals matching this string.
            + phase_id: `5` (string, optional) - Only return deals with this phase ID
            + company_id: `123` (string, optional) - Only return deals for this company
            + contact_id: `456` (string, optional) - Only return deals for this contact
            + responsible_user_id: `456` (string, optional) - Only return deals for this user
        + sort (array, optional)
            + (object)
                + field: `created_at` (enum[string], required)
                    + Members
                        + created_at
                    + Default: `created_at`
                + order: `desc` (enum[string], optional)
                    + Members
                        + desc
                    + Default: `created_at`

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `164938` (string)
                + title: `Interesting deal` (string)
                + status: `won` (enum[string])
                    + Members
                        + open
                        + won
                        + lost
                + customer (object)
                    + _type: `contact`
                    + id: 1 (string)
                + estimated_value (Money)
                + estimated_closing_date: `2017-05-09` (string)
                + estimated_probability: `0.5` (number)
                + phase (object)
                    + _type: `dealPhase`
                    + id: 1 (string)
                + responsible_user (object)
                    + _type: `user`
                    + id: 1 (string)
                + created_at: `2017-05-09T11:25:11+00:00` (string)
                + last_activity_at: `2017-05-09T11:30:58+00:00` (string)
                + closed_at: `2017-05-09T11:31:30+00:00` (string)
                + reason_lost: `No interest` (string)
                + source: `Facebook` (string)
                + custom_fields (object)
                    + _items (array)
                        + (object)
                            + field (object)
                                + _type: `customField`
                                + id: 123 (string)
                            + value: `092980616`

### deals.info [GET /deals.info]

Get details for a single deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + id: `164938` (string)
        + title: `Interesting deal` (string)
        + status: `won` (enum[string])
            + Members
                + open
                + won
                + lost
        + customer (object)
            + _type: `contact` (string)
            + id: 123 (string)
        + estimated_value (Money)
        + estimated_closing_date: `2017-05-09` (string)
        + estimated_probability: `0.5` (number)
        + phase (object)
            + _type: dealPhase (string)
            + id: `5` (string)
        + responsible_user (object)
            + _type: user (string)
            + id: 17 (string)
        + created_at: `2017-05-09T11:25:11+00:00` (string)
        + last_activity_at: `2017-05-09T11:30:58+00:00` (string)
        + closed_at: `2017-05-09T11:31:30+00:00` (string)
        + reason_lost: `No interest` (string)
        + source: `Facebook` (string)
        + custom_fields (object)
            + _items (array)
                + (object)
                    + field (object)
                        + _type: `customField`
                        + id: 123 (string)
                    + value: `092980616`
        + phase_history/phases/history (object)
            + _items (array)
                + (object)
                    + phase (object)
                        + _type: dealPhase (string)
                        + id: `1` (string)
                    + started_by (object)
                        + _type: user (string)
                        + id: `5` (string)
                    + started_at: `2017-05-01 12:00:00` (string)
                    + ended_at: `2017-05-01 12:00:00` (string)

### deals.create [POST /deals.create]

Create a new deal for a customer.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + customer (object)
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id: 123 (string)
        + title: `Interesting business deal` (string, required)
        + source: `Facebook` (string, required)
        + department_id: `1` (string, optional)
        + responsible_user_id: `1` (string, optional)
        + phase_id: `1` (string, optional)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional)
        + estimated_closing_date: `2017-05-09` (string, optional)
        + custom_fields (array)
            + (object)
                + field_id: 123 (string)
                + value

+ Response 201 (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string)

### deals.update [POST /deals.update]

Update a deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + title: `Interesting business deal` (string, optional)
        + source: `Google Adwords` (string, optional)
        + department_id: `1` (string, optional)
        + responsible_user_id: `1` (string, optional)
        + estimated_value (Money, optional)
        + estimated_probability: `0.75` (number, optional)
        + estimated_closing_date: `2017-05-09` (string, optional)
        + custom_fields (array)
            + (object)
                + field_id: 123 (string)
                + value

+ Response 204

### deals.changePhase [POST /deals.changePhase]

Change the phase of a deal.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + phase_id: `1` (string, optional)

+ Response 204

### deals.won [POST /deals.won]

Mark a deal as won.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)

+ Response 204

### deals.lost [POST /deals.lost]

Mark a deal as lost.

+ Request (application/json;charset=utf-8)

    + Attributes (object)
        + id: `1` (string, required)
        + reason: `Bad product fit` (string, optional)

+ Response 204

### dealPhases.list [GET /dealPhases.list]

Get a list of all phases a deal can go through.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: 1 (string)
                + name: `New` (string)

### dealSources.list [GET /dealSources.list]

Get a list of all deal sources.

+ Response 200 (application/json;charset=utf-8)

    + Attributes (object)
        + _items: Facebook, Twitter (array[string])
