## Deals [/deals]

### deals.list [GET /deals.list]

Get a list of all deals

+ Request (application/json)

    + Attributes (object)
        + page (object, optional)
            + size: `10` (number, optional) - Amount of results you want
                + Default: `20`
            + number: `1` (number, optional) - Page of results you want
                + Default: `1`
        + filter (object, optional)
            + term: `Teamleader` (string, optional) - A search string. Teamleader will try to search deals matching this string.
            + phase_id: `5` (number, optional) - Only return deals with this phase ID
            + company_id: `123` (number, optional) - Only return deals for this company
            + contact_id: `456` (number, optional) - Only return deals for this contact
            + project_id: `789` (number, optional) - Only return deals for this project

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `164938` (number)
                + title: `Interesting deal` (string)
                + customer (object)
                    + id: `contact-1` (string)
                    + name: John Smith (string)
                + probability: `5` (number)
                + phase_id: `5` (number)
                + responsible_user (object)
                    + id: 17
                + entry_date: `2017-05-09T11:25:11+00:00` (string)
                + latest_activity_date: `2017-05-09T11:30:58+00:00` (string)
                + close_date: `2017-05-09T11:31:15+00:00` (string)
                + date_lost: `2017-05-09T11:31:30+00:00` (string)
                + reason_refused: `No interest` (string)
                + source_id: `8799` (number)

### deals.info [GET /deals.info{?embed}]

Get deal details

+ Request (application/json)

    + Parameters
        + embed: `quotation,phase_changes` (string, optional) - Comma separated string with additional data you wish to include

    + Attributes (object)
        + deal_id: `1` (number, required) - ID of the deal you want

+ Response 200 (application/json)

    + Attributes (object)
        + id: `164938` (number)
        + title: `Interesting deal` (string)
        + quotation_nr: `21` (number)
        + customer (object)
            + id: `contact-1` (string)
            + name: John Smith (string)
        + total_price_excl_vat: `0.00` (number)
        + probability: `5` (number)
        + phase (object)
            + id: `5` (number)
        + responsible_user (object)
            + id: 17
        + entry_date: `2017-05-09T11:25:11+00:00` (string)
        + latest_activity_date: `2017-05-09T11:30:58+00:00` (string)
        + close_date: `2017-05-09T11:31:15+00:00` (string)
        + date_lost: `2017-05-09T11:31:30+00:00` (string)
        + reason_refused: `No interest` (string)
        + source (object)
            + id : `8799` (number)
        + quotation (object)
            + quotation_nr: `21` (number)
            + total_price_excl_vat: `0.00` (number)
            + items (object)
                + _items(array)
                    + (object)
                        + price: `5` (number)
                        + amount: `1` (number)
                        + vat: `21` (string) - The vat tariff for this line
                        + product (object)
                            + id: `1` (number) - ID of the product
                        + account: `1` (number) - ID of the bookkeeping account
                        + subtitle: `Enable search` (string)
        + phase_changes (object)
            + _items (array)
                + (object)
                    + old_phase (object)
                        + id: `1` (number)
                    + new_phase (object)
                        + id: `2` (number)
                    + change_date: `2017-05-01 12:00:00` (string)
                    + changed_by (object)
                        + id: `5` (number)

### deals.create [POST /deals.create]

Create a deal for a contact or company.

+ Request (application/json)

    + Attributes (object)
        + contact_or_company: `company` (enum[string], required) - Who is related to this deal?
            + Members
                + company
                + contact
        + contact_or_company_id: `1` (number, required) - ID of the related contact or company
        + title: `Interesting business deal` (string, required)
        + source: `Google Adwords` (string, required)
        + custom_field_ID: `1` (number, optional) - replace ID by the ID of your custom field.
        + sys_department_id: `1` (number, optional) - ID of the department the deal will be added to
        + responsible_sys_client_id: `1` (number, optional) - ID of the user that is responsible for this deal
        + phase_id: `1` (number, optional) - Phase ID of the initial deal phase
        + description: `1` (string, optional) - If this parameter is filled out a quotation (PDF) is generated by Teamleader using the text provided and the items. The PDF is accessible via the web interface.
        + budget_estimation: `10` (number, optional) - budget estimation for this deal. This value will be overwritten once a quotation is made for this deal
        + optional_contact_id: `1` (number, optional) - if this deal is related to a company, you can specify the ID of a related contact within that company via this parameter
        + filter_double_sales: `0` (number, optional) - if set to 1, an extra check added to make sure the deal isn't a double of the previous one.'

+ Response 201 (application/json)

    + Attributes (object)
        + id: `1` (number)

### deals.update [POST /deals.update]

Update a deal.

+ Request (application/json)

    + Attributes (object)
        + deal_id: `1` (number, required) - Who is related to this deal?
        + title: `Interesting business deal` (string, optional)
        + source: `Google Adwords` (string, optional)
        + responsible_sys_client_id: `1` (number, optional) - ID of the user that is responsible for this deal
        + budget_estimation: `10` (number, optional) - budget estimation for this deal. This value will be overwritten once a quotation is made for this deal
        + custom_field_ID: `1` (number, optional) - replace ID by the ID of your custom field.

+ Response 204

### deals.changePhase [POST /deals.changePhase]

Move a deal to a new phase.

+ Request (application/json)

    + Attributes (object)
        + deal_id: `1` (number, required) - Who is related to this deal?
        + phase_id: `1` (number, optional) - new phase ID this deal should be moved to

+ Response 204

### deals.quotations.add [POST /deals.quotations.add]

Add a quotation to a deal

+ Request (application/json)

    + Attributes (object)
        + deal_id: `1` (number, required) - Who is related to this deal?
        + items (array[object])
            + (object)
                + description: `Search module` (string, required)
                + price: `5` (number, required)
                + amount: `1` (number, required)
                + vat: `21` (string, required) - The vat tariff for this line
                + product_id: `1` (number, optional) - ID of the product
                + account: `1` (number, optional) - ID of the bookkeeping account
                + subtitle: `Enable search` (string, optional)

+ Response 204

+ Response 400

        A quotation can only be added once

### deals.quotations.update [POST /deals.quotations.update]

Update a deal quotation's items

+ Request (application/json)

    + Attributes (object)
        + deal_id: `1` (number, required) - Who is related to this deal?
        + items (array[object]) - Replaces a deals previous items
            + (object)
                + description: `Search module` (string, required)
                + price: `5` (number, required)
                + amount: `1` (number, required)
                + vat: `21` (string, required) - The vat tariff for this line
                + product_id: `1` (number, optional) - ID of the product
                + account: `1` (number, optional) - ID of the bookkeeping account
                + subtitle: `Enable search` (string, optional)

+ Response 204

### deals.quotations.send [POST /deals.quotations.emailToClient]

Send a deal's quotation via email to a client

+ Request (application/json)

    + Attributes (object)
        + sale_id: `1` (number, required) - ID of the deal
        + email: `john@example.com` (string, required) - Email of the client
        + subject: `1` (number, required) - Subject of the email
        + message: `1` (number, required) -  Add <link> to the message to print out the InvoiceCloud link. (not required when using an email template, leave empty or discard from request when using template_id)
        + template_id: `1` (number, optional) - ID of the email message created in Teamleader.

+ Response 204

### dealPhases.list [GET /dealPhases.list]

Get a list of all phases a deal can go through

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: 1 (number)
                + name: `New` (string)

### dealSources.list [GET /dealSources.list]

Get a list of all deal sources

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: 1 (number)
                + name: `Google Search` (string)
