## Departments [/departments]

### departments.list [GET /departments.list]

Get a list of all departments

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + _type: `department` (string)
                + id: `42` (number)
                + name: `Human Resources` (string)
                + name_short: `HR` (string)
                + email: `hr@example.com` (string)
                + invoicing_email: `invoicing@example.com` (string)
                + website: `http://example.com` (string)
                + phone: `1234567` (string)
                + fax: `7654321` (string)
                + address (Address)
                + vat_number: `BE0899623035` (string)
                + local_business_number: `63326426` (string)
                + bank_name: `Bank of Switzerland` (string)
                + iban: `BE12 1234 1234 1234` (string)
                + bic: `BICBANK` (string)
                + interest_rate: `12` (number)
                + late_fee: `12` (number)
                + minimum_late_fee: `12` (number)
                + registration_number: `12` (number)

### departments.add [POST /departments.add]

Add a department

+ Request (application/json)

    + Attributes (object)
        + name: `Human Resources` (string, required)
        + name_short: `HR` (string)
        + email: `hr@example.com` (string, required)
        + invoicing_email: `invoicing@example.com` (string) - Automatic invoice reminders are sent from this e-mail address
        + website: `http://example.com` (string)
        + phone: `1234567` (string)
        + fax: `7654321` (string)
        + address (Address, required)
        + vat_number: `BE0899623035` (string)
        + local_business_number: `63326426` (string) - Local business number (KVK in the Netherlands)
        + bank_name: `Bank of Switzerland` (string)
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string)
        + interest_rate: `12` (number) - Interest rate (percentage)
        + late_fee: `12` (number) - Late fee (percentage)
        + minimum_late_fee: `12` (number) - Minimum late fee
        + registration_number: `12` (number)

+ Response 201 (application/json)

    + Attributes
        + data (object)
            + id: `1` (number)

### departments.update [POST /departments.update]

Update a department

+ Request (application/json)

    + Attributes (object)
        + department_id: `42` (number, required)
        + name: `Human Resources` (string)
        + name_short: `HR` (string)
        + email: `hr@example.com` (string)
        + invoicing_email: `invoicing@example.com` (string) - Automatic invoice reminders are sent from this e-mail address
        + website: `http://example.com` (string)
        + phone: `1234567` (string)
        + fax: `7654321` (string)
        + address (Address)
        + vat_number: `BE0899623035` (string)
        + local_business_number: `63326426` (string) - Local business number (KVK in the Netherlands)
        + bank_name: `Bank of Switzerland` (string)
        + iban: `BE12 1234 1234 1234` (string)
        + bic: `BICBANK` (string)
        + interest_rate: `12` (number) - Interest rate (percentage)
        + late_fee: `12` (number) - Late fee (percentage)
        + minimum_late_fee: `12` (number) - Minimum late fee
        + registration_number: `12` (number)

+ Response 204
