## Files [/files]

### files.list [GET /files.list]

Get a list of all files relating to an object

+ Request (application/json)

    + Attributes (object)
        + amount: `20` (number, required) - The amount of contacts returned per request, max 1 to 100
        + pageno: `0` (number, required) - The current page, the first page is 0
        + object_type: `contact` (enum[string], required) - The type of object
            + Members
                + contact
                + company
                + sale
                + ticket
                + project
                + meeting
        + object_id: `1` (number, required) - ID of the object
        + folder_name: `cat_pictures` (string, optional) - the folder name of which the contents should be displayed

+ Response 200 (application/json)

    + Attributes (object)
        + data (array)
            + (object)
                + id: `101` (number)
                + filename: `cat.bmp` (string)
                + date_last_edited: `1492673227` (number)
                + filesize_bytes: `256` (number)

### files.info [GET /files.info]

Get a info about a specific file

+ Request (application/json)

    + Attributes (object)
        + file_id: `20` (number, required) - The file's ID

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + filename: `cat.bmp` (string)
            + filesize_bytes: `256` (number)
            + uploader_client_id: `1` (number)
            + related_object_type: `contact` (string)
            + related_object_id: `1` (number)
            + folder: `pics` (string)
            + date_last_edited: `2017-04-20T07:27:07+00:00` (string)

### files.download [GET /files.download]

Get a signed URL where the file can be downloaded. The signed URL will remaing valid for 30 seconds.

+ Request (application/json)

    + Attributes (object)
        + file_id: `20` (number, required) - The file's ID

+ Response 200 (application/json)

    + Attributes (object)
        + data (object)
            + signed_download_url: `http://example.com/cat.bmp` (string)

### files.upload [POST /files.upload]

Get a signed URL where the file can be downloaded. The signed URL will remaing valid for 30 seconds.

+ Request (application/json)

    + Attributes (object)
        + object_type: `contact` (enum[string], required) - The type of object
            + Members
                + contact
                + company
                + sale
                + ticket
                + project
                + meeting
        + object_id: `1` (number, required) - ID of the object
        + file_content: `TG9yZW0gSXBzdW0gaXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4=` (string, required) - Base64 encoded version the file
        + file_name: `cat.bmp` (string, required) - Name of the file, including extension
        + folder_name: `cat_pictures` (string, optional) - the folder name of which the contents should be displayed

+ Response 201 (application/json)

    + Attributes (object)
        + data (object)
            + id: `123` (number)

### files.delete [POST /files.delete]

Delete a file

+ Request (application/json)

    + Attributes (object)
        + file_id: `20` (number, required) - The file's ID

+ Response 204
