## General [/]

### users.list [GET /users.list]

Get a list of all users

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[User])

### tags.list [GET /tags.list]

Get a list of all tags

+ Response 200 (application/json)

    + Attributes (object)
        + data: expo, upsell (array[string])
