## General [/]

### users.list [GET /users.list]

Get a list of all users

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `1` (number)
                + name: `John Smith` (string)
                + email: `john@teamleader.eu` (string)
                + gsm: `+32412654321` (string)
                + phone: `+3291239843` (string)
                + team (object)
                    + id: 1 (number)
                + title: `Sales` (string)
                + active: `true` (boolean)

### tags.list [GET /tags.list]

Get a list of all tags

+ Response 200 (application/json)

    + Attributes (object)
        + _items : expo, upsell (array[string])
