## General [/]

### /users.list [GET /users.list]

Get a list of all users

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[User])

### /departments.list [GET /departments.list]

Get a list of all departments

+ Response 200 (application/json)

    + Attributes (object)
        + data (array[Department])


### tags.list [GET /tags.list]

Get a list of all tags

+ Response 200 (application/json)

        {
            "1": "A Tag",
            "2": "Another Tag",
            "3": "Tagtastic"
        }

### /segments.list [GET /segments.list]

Get a list of all segments

+ Request (application/json)

    + Attributes (object)
        + `object_type`: `crm_companies` (enum[string], required)

            Pick one of the possible values.

            + Members
                + crm_companies
                + crm_contacts
                + crm_todos
                + crm_callbacks
                + crm_meetings
                + inv_invoices
                + inv_creditnotes
                + pro_projects
                + sale_sales
                + ticket_tickets

+ Response 200 (application/json)

        {
            "Medewerkers": [
                {
                    "id": "owner--1",
                    "name": "",
                    "num_matches": -1
                },
                {
                    "id": "owner-1",
                    "name": "John Smith",
                    "num_matches": -1
                }
            ],
            "Smart segments": []
        }
