## Invoices [/invoices]

### invoices.list [GET /invoices.list]

List invoices

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + contact_id: `123` (string, optional) - The ID of the contact you wish to filter on. You can't provide a company ID.
            + company_id: `123` (string, optional) - The ID of the company you wish to filter on. You can't provide a contact ID.
            + invoice_date_from: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + invoice_date_to: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + deal_id: `1` (string, optional) - The ID of the deal you wish to filter on.
            + department_id: `1` (string, optional) - The ID of the department you wish to filter on.
            + project_id: `1` (string, optional) - The ID of the project you wish to filter on.
            + subscription_id: `1` (string, optional) - The ID of the subscription you wish to filter on.
            + status: `booked` (enum[string], optional) - Only return booked or draft invoices. Leave blank to return everything
                + Members
                    + draft
                    + booked
        + page (Page, optional)

+ Response 200 (application/json)

    + Attributes (object)
        + _items (array)
            + (object)
                + id: `173111` (string)
                + department (object)
                    + _type: `department` (string)
                    + id: `1` (string)
                + invoice_number: `2017/5` (string)
                + invoice_date: `2016-02-04` (string)
                + status: `booked` (enum[string])
                    + Members
                        + booked
                        + draft
                + due_on: `2016-03-03` (string)
                + paid: `true` (boolean)
                + paid_at: `2016-02-04T16:44:33+00:00` (string)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + address (Address)
                    + vat_number: `BE0899623035` (string)
                    + customer (object)
                        + _type: `contact` (string)
                        + id: `123` (string)
                    + for_attention_of (object)
                        + name: `Radja Nainggolan` (string)
                        + contact (object)
                            + _type: `contact` (string)
                            + id: `456` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)
                    + withheld_taxes (array)
                        + (object)
                            + type: `Trabajo`
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)

### invoices.info [GET /invoices.info]

Get a single invoice.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string)

+ Response 200 (application/json)

    + Attributes (object)
        + id: `173111` (string)
        + department (object)
            + _type: `department` (string)
            + id: `1` (string)
        + invoice_number: `2017/5` (string)
        + invoice_date: `2016-02-04` (string)
        + status: `booked` (enum[string])
            + Members
                + booked
                + draft
        + due_on: `2016-03-03` (string)
        + paid: true (boolean)
        + paid_at: `2016-02-04T16:44:33+00:00` (string)
        + invoicee (object)
            + name: `De Rode Duivels` (string)
            + address (Address)
            + vat_number: `BE0899623035` (string)
            + customer (object)
                + _type: `contact` (string)
                + id: `123` (string)
            + for_attention_of (object)
                + name: `Radja Nainggolan` (string)
                + contact (object)
                    + _type: `contact` (string)
                    + id: `456` (string)
        + grouped_lines (array[InvoiceLineItemGroup], optional)
        + payments (array)
            + (object)
                + _type `payment` (string)
                + id (string)
                + amount (Money)
                + paid_at (string)
        + total (object)
            + tax_exclusive (Money)
            + tax_inclusive (Money)
            + payable (Money)
            + taxes (array)
                + (object)
                    + rate: `0.21` (number)
                    + taxable (Money)
                    + tax (Money)
            + withheld_taxes (array)
                + (object)
                    + type: `Trabajo`
                    + rate: `0.21` (number)
                    + taxable (Money)
                    + tax (Money)

### invoices.draft [POST /invoices.draft]

Draft a new invoice

+ Request (application/json)

    + Attributes (object)
        + customer (object, optional) - Who is the invoice for?
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id (string)
        + for_attention_of (object, optional)
            + name (string, optional)
            + contact_id (string, optional)
        + department_id (string) - Id of the department the invoice will be added to
        + payment_term (object, optional)
            + type (enum[string])
                + Members
                    + cash - Direct payment, often cash
                    + end_of_month - End of the month of Xth day after the invoice date
                    + after_invoice_date - X days after invoice date
            + days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
        + layout_id (string, optional) - Id of the layout you wish to use for this invoice
        + purchase_order_number (string, optional) - The external order number. Overrides possible PO number coming from project.
        + remarks (string, optional) - Free form text. Visible on the invoice depending on the template.
        + grouped_lines (array[InvoiceLineItemGroup], optional)

+ Response 201 (application/json)

    + Attributes (object)
        + id: `1` (string) - ID of the invoice that was created

### invoices.update [POST /invoices.update]

Update an existing invoice. Not possible for declared invoices.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `123` (string)
        + customer (object, optional) - Who is the invoice for?
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id (string)
        + for_attention_of (object, optional)
            + name (string, optional)
            + contact_id (string, optional)
        + department_id (string) - Id of the department the invoice will be added to
        + payment_term (object, optional)
            + type (enum[string])
                + Members
                    + cash - Direct payment, often cash
                    + end_of_month - End of the month of Xth day after the invoice date
                    + after_invoice_date - X days after invoice date
            + days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
        + layout_id (string, optional) - Id of the layout you wish to use for this invoice
        + purchase_order_number (string, optional) - The external order number. Overrides possible PO number coming from project.
        + remarks (string, optional) - Free form text. Visible on the invoice depending on the template.
        + grouped_lines (array[InvoiceLineItemGroup], optional)

+ Response 204

### invoices.delete [POST /invoices.delete]

Delete an existing invoice. Only possible for draft invoices or the last booked invoice.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)

+ Response 204

### invoices.book [POST /invoices.book]

Book a draft invoice.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)
        + invoice_date: `2016-02-04` (string, optional)

+ Response 204

### invoices.download [POST /invoices.download]

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)
        + format: `pdf` (enum[string], required)
            + Members
                + pdf

### invoices.declare [POST /invoices.declare]

Declare a booked invoice, locking the invoice for future changes.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)

+ Response 204

### invoices.registerPayment [POST /invoices.registerPayment]

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)
        + amount (Money, optional)
        + paid_at: `2016-02-04T16:44:33+00:00` (string, optional)

+ Response 201 (application/json)

    + Attributes (object)
        + id: `2` (string) - ID of the payment that was created

### invoices.removePayment [POST /invoices.removePayment]

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)
        + payment_id: `2` (string, required)

### invoices.credit [POST /invoices.credit]

Create a credit note from an invoice. Only possible for booked and declared invoices.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (string, required)

+ Response 201 (application/json)

    + Attributes (object)
        + _type: `creditNote` (string)
        + id: `1` (string) - ID of the credit note that was created

### creditNotes.draft [POST /creditNotes.draft]

Create a draft credit note.

+ Request (application/json)

    + Attributes (object)
        + invoice_id (string, optional)
        + customer (object, optional)
            + type (enum[string])
                + Members
                    + contact
                    + company
            + id (string)
        + for_attention_of (object, optional)
            + name (string, optional)
            + contact_id (string, optional)
        + department_id (string)
        + payment_term (object, optional)
            + type (enum[string])
                + Members
                    + cash - Direct payment, often cash
                    + end_of_month - End of the month of Xth day after the invoice date
                    + after_invoice_date - X days after invoice date
            + days (number, optional) - Modifier "X" for the above statements. Not required when type is 'cash'.
        + layout_id (string, optional) - Id of the layout you wish to use for this invoice
        + purchase_order_number (string, optional) - The external order number. Overrides possible PO number coming from project.
        + remarks (string, optional) - Free form text. Visible on the invoice depending on the template.
        + grouped_lines (array[InvoiceLineItemGroup], optional)

### creditNotes.list [GET /creditNotes.list]

List credit notes

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + contact_id: `123` (string, optional) - The ID of the contact you wish to filter on. You can't provide a company ID.
            + company_id: `123` (string, optional) - The ID of the company you wish to filter on. You can't provide a contact ID.
            + date_from: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + date_to: `2016-01-01` (string, optional) - yyyy-mm-dd
            + department_id: `1` (string, optional) - The ID of the department you wish to filter on.
            + project_id: `1` (string, optional) - The ID of the project you wish to filter on.
            + invoice_id: `1` (string, optional) - The ID of the invoice you wih to filter on.
        + page (Page, optional)


+ Response 200 (application/json)

    + Attributes (object)
        + _items (array[object])
            + (object)
                + id: `173111` (string)
                + department (object)
                    + _type: `department` (string)
                    + id: `1` (string)
                + invoice (object)
                    + _type: `invoice` (string)
                    + id: `1` (string)
                + credit_note_number: `2017/5` (string)
                + paid: `true` (boolean)
                + paid_at: `2016-03-03T16:44:33+00:00` (string)
                + total (object)
                    + tax_exclusive (Money)
                    + tax_inclusive (Money)
                    + payable (Money)
                    + taxes (array)
                        + (object)
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)
                    + withheld_taxes (array)
                        + (object)
                            + type: `Trabajo`
                            + rate: `0.21` (number)
                            + taxable (Money)
                            + tax (Money)
                + invoicee (object)
                    + name: `De Rode Duivels` (string)
                    + address (Address)
                    + vat_number: `BE0899623035` (string)
                    + customer (object)
                        + _type: `contact` (string)
                        + id: `123` (string)
                    + for_attention_of (object)
                        + name: `Radja Nainggolan` (string)
                        + contact (object)
                            + _type: `contact` (string)
                            + id: `456` (string)

### creditNotes.update [POST /creditNotes.update]

### creditNotes.book [POST /creditNotes.book]

### taxRates.list [GET /taxRates.list]
