## Invoices [/invoices]

### invoices.list [GET /invoices.list]

List invoices

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + customer (object, optional) - Use this to filter by customer
                + type: `contact` (enum[string], required) 
                    + Members
                        + contact
                        + company
                + id: `1` (number, required) - ID of the contact or company
            + date_from: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + date_to: `2016-01-01` (string, optional) - yyyy-mm-dd
            + deal_id: `1` (number, optional) - The ID of the deal you wish to filter on.
            + department_id: `1` (number, optional) - The ID of the department you wish to filter on.
            + project_id: `1` (number, optional) - The ID of the project you wish to filter on.
            + subscription_id: `1` (number, optional) - The ID of the subscription you wish to filter on.
            + status: `booked`  (enum[string], optional) - Only return booked or draft invoices. Leave blank to return everything
                + Members
                    + booked
                    + draft
        + page (object, optional)
            + size: `20` (number, optional) - Amount of invoices you want returned, 1 to 100.
                + Default: `20`
            + number: `1` (number, optional) - The numerated page you want, starts at 1.
                + Default: `1`
                
+ Response 200 (application/json)

    + Attributes (object)
        data (array[Invoice])

### creditNotes.list [GET /creditNotes.list]

List credit notes

+ Request (application/json)

    + Attributes (object)
        + filter (object, optional)
            + customer (object, optional) - Use this to filter by customer
                + type: `contact` (enum[string], required) 
                    + Members
                        + contact
                        + company
                + id: `1` (number, required) - ID of the contact or company
            + date_from: `2016-01-01` (string, optional) - Format: yyyy-mm-dd
            + date_to: `2016-01-01` (string, optional) - yyyy-mm-dd
            + department_id: `1` (number, optional) - The ID of the department you wish to filter on.
            + project_id: `1` (number, optional) - The ID of the project you wish to filter on.
        + page (object, optional)
            + size: `20` (number, optional) - Amount of credit notes you want returned, 1 to 100.
                + Default: `20`
            + number: `1` (number, optional) - The numerated page you want, starts at 1.
                + Default: `1`
                
+ Response 200 (application/json)

    + Attributes (array[CreditNote])
