## Meetings [/meetings]

### meetings.delete [POST /meetings.delete]

Delete a meeting from Teamleader

+ Request (application/json)

    + Attributes (object)
        + meeting_id: `1` (number, required) - The ID of the meeting you wish to delete

+ Response 204
