## Quotations [/quotations]

### quotations.add [POST /quotations.add]

Add a quotation to a deal

+ Request (application/json)

    + Attributes (object)
        + deal_id: `1` (string, required)
        + xxx (array[InvoiceLineItem], required)

+ Response 204

### quotations.update [POST /quotations.update]

Update a deal quotation's items

+ Request (application/json)

    + Attributes (object)
        + quotation_id: `1` (string, required)
        + deal_id: `1` (string, optional)
        + xxx (array[InvoiceLineItem], optional)

+ Response 204

### quotations.info [GET /quotations.info]

Get a quotation

+ Request (application/json)

    + Attributes (object)
        + quotation_id: `1` (string, required)

+ Response 200 (application/json)

    + Attributes (object)
        + quotation_id: `1` (string)
        + deal_id: `1` (string)
        + xxx (array[InvoiceLineItem])

### quotations.send [POST /quotations.send]

Send a deal's quotation to a client via email.

+ Request (application/json)

    + Attributes (object)
        + quotation_id: `1` (string, required)
        + email: `john@example.com` (string, required) - The email recipient
        + subject: Your quotation` (string, required) - The email subject
        + message: `1` (string, required) - The email body
        + template_id: `1` (string, optional)

+ Response 204
